FROM --platform=linux/amd64 maven:3.9.6-eclipse-temurin-17 AS builder

WORKDIR /app

COPY api/adapter /app

RUN chmod -R 777 /app

RUN mvn clean package -DskipTests

FROM --platform=linux/amd64 eclipse-temurin:17-jre

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

RUN chmod 777 app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
